// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avtrwggqjfauoborotqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2dHJ3Z2dxamZhdW9ib3JvdHFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzcwNDAsImV4cCI6MjA2ODg1MzA0MH0.tUb6PLVq6K_d8nsT6JEvHN5E8OYo9NAceBXgoWdKaHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});